
# general build configuration would go here

env:
  global:
  # encrypted CF_PASSWORD

  deploy:
  provider: script
  # https://github.com/travis-ci/travis-ci/issues/5538#issuecomment-265956466
  script: bash deploy.sh
  skip_cleanup: true
  on:
    branch: master